    scripts:
      - name: Install dependencies
        script: |
          python3 -m pip install --upgrade pip
          pip3 install flet
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      - name: Build APK with Flet
        script: |
          flet build apk
