workflows:
  flet-android-build:
    name: Build Flet Android APK
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        PYTHON_VERSION: "3.10"
        FLET_BUILD_NO_PROMPT: "1"   # empêche les questions interactives
    scripts:
      - name: Install dependencies
        script: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install -r requirements.txt
          pip3 install flet-cli
      - name: Build APK with Flet
        script: |
          flet build apk --no-prompt
    artifacts:
      - build/apk/*.apk
      - build/app/outputs/flutter-apk/*.apk
