name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Pre-installation de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Installation des dependances Python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install flet; fi

      - name: Compilation APK
        run: |
          flet build apk --icon assets/icons.png -v

      - name: Recuperation de l APK
        uses: actions/upload-artifact@v4
        with:
          name: cyberShudule-APK
          path: build/apk/*.apk