name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet & Packaging tools
        run: |
          pip install flet cookiecutter

      - name: Build APK with Flet
        run: |
          flet build apk --icon assets/icons.png

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CyberSchedule-APK
          path: build/apk/*.apk
